# Generated by Django 3.1.2 on 2020-10-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myawwards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
